title = "Kontrazis Petros -  XR Developer"
baseURL = ""
languageCode = "en-us"
theme = "gohugo-theme-ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "My personal Web page"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/petrosKon"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/petros-kontrazis-248739168/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/VR-Background.jpg"
  recent_posts_number = 3